language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --base-href https://github.com/ciremusyoka/refresh-token
- cp index.php .htaccess dist/refresh-token/
- cd dist/refresh-token
- ls
deploy:
  provider: heroku
  local_dir: dist/travis-demo
  app: travis-cire
